services:
  qobuz:
    build: .
    image: qobuz-downloader
    container_name: qobuz-downloader
    environment:
      - DOWNLOAD_BASE_DIR=/app/downloads
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    volumes:
      - ${HOST_DOWNLOADS_DIR:-./downloads}:/app/downloads
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-5000}:5000"
    restart: ${RESTART_POLICY:-no}
