version: '3.8'

services:
  qobuz-downloader:
    build: .
    image: qobuz-downloader:latest
    container_name: qobuz-downloader
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DOWNLOAD_BASE_DIR=/app/downloads
    volumes:
      - ./downloads:/app/downloads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
