services:
  qobuz:
    build: .
    image: qobuz-downloader
    container_name: qobuz-downloader
    ports:
      - "5000:5000"
    environment:
      - DOWNLOAD_BASE_DIR=/app/downloads
    tty: true
    stdin_open: true
    env_file:
      - .env