services:
  qobuz:
    build: .
    image: qobuz-downloader
    container_name: qobuz-downloader
    environment:
      - DOWNLOAD_BASE_DIR=/app/downloads
      # Add other env vars as needed, e.g.:
      # - LOGGING_ENABLED=true
      # - QOBUZ_API_BASE_URL=https://us.qobuz.squid.wtf
    volumes:
      - ./downloads:/app/downloads
      # Optionally mount your .env file if you want to override/add secrets:
      # - ./my.env:/app/.env
    tty: true
    stdin_open: true

    ports:
      - 5000:5000  # Expose the Flask app port